# Generated by Django 4.1 on 2022-08-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Fm', 'Female'), ('Male', 'Male'), ('Other', 'Other'), ('Prefer', 'Prefer not to say')], max_length=50),
        ),
    ]
